package hoyoMusic.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.mineapp.SongEntity;

import hoyoMusic.greendao.db.SongEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig songEntityDaoConfig;

    private final SongEntityDao songEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        songEntityDaoConfig = daoConfigMap.get(SongEntityDao.class).clone();
        songEntityDaoConfig.initIdentityScope(type);

        songEntityDao = new SongEntityDao(songEntityDaoConfig, this);

        registerDao(SongEntity.class, songEntityDao);
    }
    
    public void clear() {
        songEntityDaoConfig.clearIdentityScope();
    }

    public SongEntityDao getSongEntityDao() {
        return songEntityDao;
    }

}
